name: Release - Test, Build & Redeploy1

on:
  push:

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:headless

      - name: Build
        run: npm run build:prod
      -
        name: Login To DockerHub
        uses: docker/login-action@v1
        with:
          username: ferdibulus
          password: dckr_pat_fUa49qOK2W0QiD2tJCDWAvZeYu4
      -
        name: Push the image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags : ferdibulus/stockappview, ferdibulus/stockappview:latest
